# External resources and references

## Peer-reviewed articles 


- A Review of Bayesian Perspectives on Sample Size Derivation for Confirmatory Trials (2021). \
<https://pubmed.ncbi.nlm.nih.gov/34992303/>

- Bayesian sample size determination for diagnostic accuracy studies (2022). \
<https://onlinelibrary.wiley.com/doi/10.1002/sim.9393>

- Bayesian estimation supersedes the t test (2013). \
<https://psycnet.apa.org/doiLanding?doi=10.1037%2Fa0029146>

- The Bayesian New Statistics: Hypothesis testing, estimation, meta-analysis, and power analysis from a Bayesian perspective (2017)
<https://link.springer.com/article/10.3758/s13423-016-1221-4>

- Bayesian and mixed bayesian/likelihood criteria for sample size determination 
<https://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-0258(19970415)16:7%3C769::AID-SIM495%3E3.0.CO;2-V>



## Blog posts

- Introduction to bayesian clinical trial designs (detailed - including R code examples)\
<https://hbiostat.org/bayes/bet/design>


- Introduction to bayesian sample size calculation (including R code example)
<https://www.rdatagen.net/post/2021-06-01-bayesian-power-analysis/>


- Introduction to bayesian "power" and comparison with frequentist approaches (including R code example):\
<https://solomonkurz.netlify.app/blog/bayesian-power-analysis-part-i/>
<https://solomonkurz.netlify.app/blog/bayesian-power-analysis-part-ii/>

- Brief introduction to bayesian power - including comparison with frequentist terms:\
<https://anatomisebiostats.com/biostatistics-blog/bayesian-sample-size-estimation-in-clinical-study-design-rtcs/>

- Stopping rules using bayesian analyses
<https://statmodeling.stat.columbia.edu/2014/02/13/stopping-rules-bayesian-analysis/>
<http://varianceexplained.org/r/bayesian-ab-testing/>


## R packages and online tools

- **Package ‘SampleSizeProportions’ (2023)** \
Calculating Sample Size Requirements when Estimating the Difference Between Two Binomial Proportions
<https://cran.rstudio.com/web/packages/SampleSizeProportions/index.html>

- **Package ‘BayesPPD’ (2021)** \
Bayesian sample size determination using the power and normalized power prior for generalized linear models
<https://rdrr.io/cran/BayesPPD/man/BayesPPD-package.html>

- **Package ‘BayesPPDSurv’ (2024)** \
Bayesian power/type I error calculation and model fitting using the power prior and the normalized power prior for proportional hazards models with piecewise constant hazard. <https://cran.r-project.org/web/packages/BayesPPDSurv/index.html>

- **Package ‘BayesCTDesign’ (2021)** \
Two Arm Bayesian Clinical Trial Design with and Without Historical Control Data
<https://cran.r-project.org/web/packages/BayesCTDesign/index.html>

- **Package ‘BayesFactor’ (2024)** \
A suite of functions for computing various Bayes factors for simple designs, including contingency tables, one- and two-sample designs, one-way designs, general ANOVA designs, and linear regression.
<https://cran.r-project.org/web/packages/BayesFactor/index.html>

- **trialdesign.org** \
An online resource platform for several phase-I and phase-II designs.
<https://www.trialdesign.org>

## Author {-}

Sylvain Losdat, PhD\
Department of Clinical Research\
University of Bern\
3012 Bern, Switzerland