project:
  type: book
  output-dir: docs

editor: source
bibliography: references.bib
csl: plos-one.csl

book:
  title: "Bayesian Toolbox"
  search: false
  chapters:
    - part: index.qmd
    - part: 01-SampleSize.qmd
      chapters:	
        - 01-SampleSize-BinaryOutcome.qmd
        - 01-SampleSize-ContinuousOutcome.qmd
        - 01-SampleSize_Bayesian_power_basics_examples.qmd
    - references.qmd

format:
  html:
    css: styles.css
    html-math-method: mathjax
    toc-location: left
    toc-depth: 4  
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 450px
    theme: cosmo
    linestretch: 2
    code-fold: true
    code-summary: "Show R code"
    title-block-banner: true